const $=s=>document.querySelector(s), TIMES=['0h','6h','12h','24h','48h','96h'];
let genes=[], selected=null, original=[], lastSvg='', suggestTimer;
const fmt=n=>n==null?'—':Number(n).toLocaleString('es-CL',{maximumFractionDigits:3});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url){let r=await fetch(url);if(!r.ok)throw Error((await r.json()).error);return r.json()}
api('/api/info').then(x=>$('#status').textContent=`${fmt(x.gene_count)} genes indexados`).catch(e=>$('#status').textContent=e.message);
$('#search-button').onclick=search;
$('#query').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search()}if(e.key==='Escape')$('#results').classList.add('hidden')};
$('#query').oninput=()=>{clearTimeout(suggestTimer);suggestTimer=setTimeout(suggest,180)};
document.addEventListener('click',e=>{if(!e.target.closest('.hero'))$('#results').classList.add('hidden')});
async function suggest(){let input=$('#query').value,term=input.split(/[,;\n]/).pop().trim(),box=$('#results');if(term.length<2){box.classList.add('hidden');return}try{let rows=await api('/api/search?q='+encodeURIComponent(term));if(!rows.length){box.innerHTML='<div class="result"><small>Sin coincidencias</small></div>';box.classList.remove('hidden');return}box.innerHTML=rows.map((r,i)=>`<div class="result" data-id="${esc(r.gene_id)}"><b>${i+1}. ${esc(r.alias||r.name||r.gene_id)}</b><small>${esc(r.gene_id)} · ${esc(r.description||'Sin descripción')}</small></div>`).join('');box.classList.remove('hidden');box.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>{let parts=input.split(/([,;\n])/);parts[parts.length-1]=' '+el.dataset.id;$('#query').value=parts.join('').trim();box.classList.add('hidden');if(!/[,;\n]/.test(input))search()})}catch(e){box.classList.add('hidden')}}
function stats(g){let by={};TIMES.forEach(t=>{let v=g.expression.filter(x=>x.timepoint===t).map(x=>+x.tpm);let mean=v.length?v.reduce((a,b)=>a+b,0)/v.length:null;let sd=v.length>1?Math.sqrt(v.reduce((a,b)=>a+(b-mean)**2,0)/(v.length-1)):0;by[t]={values:v,mean,sd}});return by}
async function search(){let q=$('#query').value.trim();if(!q)return;$('#search-button').disabled=true;try{genes=await api('/api/batch?q='+encodeURIComponent(q));original=[...genes];let requested=q.split(/[,;\n]+/).filter(Boolean).length;$('#not-found').classList.toggle('hidden',genes.length===requested);$('#not-found').textContent=genes.length?`Se encontraron ${genes.length} de ${requested} términos. Revisa nombres o alias no presentes en ITAG4.0.`:'No se encontraron coincidencias.';if(genes.length){$('#empty').classList.add('hidden');$('#detail').classList.remove('hidden');render()}}catch(e){alert(e.message)}finally{$('#search-button').disabled=false}}
function render(){renderSummary();$('#multi').classList.toggle('hidden',genes.length<2);if(genes.length>1){renderHeatmap();renderMulti()}selectGene(selected&&genes.find(g=>g.gene_id===selected.gene_id)||genes[0])}
function renderSummary(){$('#summary-head').innerHTML='<tr><th>Nombre</th><th>ID ITAG4</th><th>Descripción</th>'+TIMES.map(t=>`<th>${t}</th>`).join('')+'</tr>';$('#summary-body').innerHTML=genes.map(g=>{let s=stats(g);return `<tr data-id="${esc(g.gene_id)}"><td><b>${esc(g.alias||g.name||g.gene_id)}</b></td><td>${esc(g.gene_id)}</td><td class="desc">${esc(g.description||'Sin descripción')}</td>${TIMES.map(t=>`<td class="num">${fmt(s[t].mean)}</td>`).join('')}</tr>`}).join('');document.querySelectorAll('#summary-body tr').forEach(r=>r.onclick=()=>selectGene(genes.find(g=>g.gene_id===r.dataset.id)))}
function selectGene(g){selected=g;let s=stats(g);$('#gene-id').textContent=g.gene_id;$('#gene-name').textContent=g.alias||g.name||g.gene_id;$('#description').textContent=g.description||'Sin descripción funcional en el GFF';$('#location').textContent=`${g.seqid}:${fmt(g.start)}–${fmt(g.end)} (${g.strand})`;$('#max-tpm').textContent=fmt(Math.max(...TIMES.map(t=>s[t].mean||0)));$('#tx-count').textContent=g.transcripts.length;$('#replicates').innerHTML=TIMES.map(t=>`<tr><td>${t}</td>${[0,1,2].map(i=>`<td class="num">${fmt(s[t].values[i])}</td>`).join('')}<td class="num">${fmt(s[t].mean)}</td><td class="num">${fmt(s[t].sd)}</td></tr>`).join('');$('#annotation').innerHTML=[['Nombre',g.name],['Alias',g.alias],['ID ITAG4',g.gene_id],['Cromosoma',g.seqid],['Coordenadas',`${g.start}–${g.end}`],['Hebra',g.strand],['Descripción',g.description],['Transcritos',g.transcripts.join(', ')||'No disponible']].map(x=>`<div><b>${x[0]}</b>${esc(x[1]||'No disponible')}</div>`).join('');lastSvg=lineSvg([{name:g.alias||g.gene_id,stats:s}],true);$('#chart').innerHTML=lastSvg}
function lineSvg(series,error=false){let W=850,H=330,p={l:65,r:25,t:30,b:55},all=series.flatMap(x=>TIMES.map(t=>(x.stats[t].mean||0)+(x.stats[t].sd||0))),max=Math.max(...all,1),x=i=>p.l+i*(W-p.l-p.r)/(TIMES.length-1),y=v=>H-p.b-v/max*(H-p.t-p.b),colors=['#0f7659','#c1522b','#4467a8','#8b5aa5','#aa8b19','#168a8a','#444'];let grid=TIMES.map((t,i)=>`<line x1="${x(i)}" y1="${p.t}" x2="${x(i)}" y2="${H-p.b}" stroke="#e5e8e2"/><text x="${x(i)}" y="${H-22}" text-anchor="middle">${t}</text>`).join('');let paths=series.map((q,j)=>{let pts=TIMES.map((t,i)=>`${x(i)},${y(q.stats[t].mean||0)}`).join(' '),c=colors[j%colors.length],bars=error?TIMES.map((t,i)=>{let m=q.stats[t].mean||0,sd=q.stats[t].sd||0;return `<line x1="${x(i)}" y1="${y(m-sd)}" x2="${x(i)}" y2="${y(m+sd)}" stroke="${c}"/><line x1="${x(i)-5}" y1="${y(m-sd)}" x2="${x(i)+5}" y2="${y(m-sd)}" stroke="${c}"/><line x1="${x(i)-5}" y1="${y(m+sd)}" x2="${x(i)+5}" y2="${y(m+sd)}" stroke="${c}"/>`}).join(''):'';let dots=TIMES.map((t,i)=>q.stats[t].values.map((v,k)=>`<circle cx="${x(i)+(k-1)*5}" cy="${y(v)}" r="3" fill="${c}" opacity=".6"/>`).join('')).join('');return `<polyline points="${pts}" fill="none" stroke="${c}" stroke-width="3"/>${bars}${dots}<text x="${p.l+10}" y="${15+j*16}" fill="${c}">${esc(q.name)}</text>`}).join('');return `<svg class="svg-chart" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg"><style>text{font:12px Verdana;fill:#53605b}</style><line x1="${p.l}" y1="${p.t}" x2="${p.l}" y2="${H-p.b}" stroke="#59645f"/>${grid}${paths}<text transform="translate(18 ${H/2}) rotate(-90)" text-anchor="middle">TPM promedio</text></svg>`}
function renderMulti(){let s=genes.map(g=>({name:g.alias||g.gene_id,stats:stats(g)}));$('#multi-chart').innerHTML=lineSvg(s);}
function renderHeatmap(){let maxima=genes.map(g=>Math.max(...TIMES.map(t=>stats(g)[t].mean||0),1));$('#heatmap').innerHTML=`<div class="heat-cell"><span></span>${TIMES.map(t=>`<span><b>${t}</b></span>`).join('')}</div>`+genes.map((g,j)=>{let s=stats(g);return `<div class="heat-cell"><span class="heat-gene">${esc(g.alias||g.gene_id)}</span>${TIMES.map(t=>{let v=s[t].mean;let a=v==null?0:v/maxima[j];return `<span title="${fmt(v)} TPM" style="background:${v==null?'#eee':`rgba(15,118,89,${.12+.88*a})`};color:${a>.55?'white':'#162621'}">${fmt(v)}</span>`}).join('')}</div>`}).join('')}
$('#sort').onchange=e=>{let mode=e.target.value;if(mode==='manual')genes=[...original];if(mode==='max')genes.sort((a,b)=>Math.max(...TIMES.map(t=>stats(b)[t].mean||0))-Math.max(...TIMES.map(t=>stats(a)[t].mean||0)));if(mode==='fold')genes.sort((a,b)=>fold(b)-fold(a));if(mode==='similarity')genes.sort((a,b)=>peak(a)-peak(b));render()};const fold=g=>{let s=stats(g),a=s['0h'].mean||.0001;return Math.max(...TIMES.map(t=>s[t].mean||0))/a},peak=g=>{let s=stats(g);return TIMES.map(t=>s[t].mean||0).indexOf(Math.max(...TIMES.map(t=>s[t].mean||0)))};
function tableRows(){return [['Nombre','ID ITAG4','Descripción',...TIMES],...genes.map(g=>{let s=stats(g);return [g.alias||g.name,g.gene_id,g.description,...TIMES.map(t=>s[t].mean)]})]};function blob(text,type,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#csv').onclick=()=>blob('\ufeff'+tableRows().map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv','expresion_75mM.csv');$('#excel').onclick=()=>blob(`<table>${tableRows().map(r=>'<tr>'+r.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>').join('')}</table>`,'application/vnd.ms-excel','expresion_75mM.xls');$('#svg').onclick=()=>blob(lastSvg,'image/svg+xml','perfil_expresion.svg');$('#png').onclick=()=>{let img=new Image();img.onload=()=>{let c=document.createElement('canvas');c.width=1700;c.height=660;c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{let u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='perfil_expresion.png';a.click();URL.revokeObjectURL(u)})};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(lastSvg)};$('#pdf').onclick=()=>window.print();
